## EXERCISES

### Vector Multiplication
1. Produce 2 vectors, one with integers in the range [5,10] and the other [15,20] using the np.arange function
1. Without using any functions from the numpy module
    1. Compute the outer product of those vectors 
    1. Compute the "trace" of the resulting matrix
    
    ![trace](https://wikimedia.org/api/rest_v1/media/math/render/svg/3e5b6e82272fc5eeca6d510388e0a2bd0a6c6463)
    
    
Complete the same items using numpy operations

In [6]:
import numpy as np
from numpy import pi
import matplotlib.pyplot as plt
from scipy.stats import norm

# 1 
x = np.arange(5,11)
print(x)
y = np.arange(15,21)
print(y)

# 2A 
c_out = [[x[i]*y[j] for j in range(len(y))]for i in range(len(x))]
print('Outer Product:') # Print Output
print(c_out)

n_out = np.outer(x,y)
print(n_out)

# 2B
# trace of outer product of 2 vectors is the inner product of the 2 vectors

np.trace(n_out)

c_trace = [x[i]*y[i] for i in range(len(x))]
print (sum(c_trace))

[ 5  6  7  8  9 10]
[15 16 17 18 19 20]
Outer Product:
[[75, 80, 85, 90, 95, 100], [90, 96, 102, 108, 114, 120], [105, 112, 119, 126, 133, 140], [120, 128, 136, 144, 152, 160], [135, 144, 153, 162, 171, 180], [150, 160, 170, 180, 190, 200]]
[[ 75  80  85  90  95 100]
 [ 90  96 102 108 114 120]
 [105 112 119 126 133 140]
 [120 128 136 144 152 160]
 [135 144 153 162 171 180]
 [150 160 170 180 190 200]]
805


### Matrix Multiplication
* Two matricies can be multiplied if their inner dimensions match (eg. 2x3 * 3x5 -> 2x5). The best rule for working with and mutliplying matricies is to remember (rows x columns). This applies to both the dimensions of a matrix (a 2x3 matrix has 2 rows and 3 columns) as well as multiplication (you multiply the rows of the first matrix by the columns of the second). 

* When multiplying two matricies of dimension (M x N)*(N x P) the resulting matrix is (M x P). The upper element of the reslting matrix is the inner (or dot) product of the first row of the first matrix and the first column of the second matrix

![two matrices](https://wikimedia.org/api/rest_v1/media/math/render/svg/16b1644351bc2041175b19cbc65da03ef78130c7)

![store product in matrix C](https://wikimedia.org/api/rest_v1/media/math/render/svg/00ac0c831c365b7424cc43239aae8cebea27c56c)

![matrix multiply](https://wikimedia.org/api/rest_v1/media/math/render/svg/3cfeccef1c8c7e6da0ddf08daed8dbf3c6f50c5e)

for i = 1, ..., n and j = 1, ..., p.

1. Make two matrices of random numbers (A and B). A should be a 4x3 matrix and B should be a 3x5 matrix. Multiply A by B using (to a resulting matrix C) using:
    1. a conventional for-loop
    1. list comprehension
    1. numpy operator
    
2. After you have C, pull out the upper quadrant using fancy indexing, and then replace the main diagonal (upper left to lower right) with 0s. 

In [54]:
#1
A = np.round(np.random.rand(4,3)*10)
print(A)

B = np.round(np.random.rand(3,5)*10)
print(B)
  
#1A

#C = [] # final result
#for i in range(len(A)):
#    row = [] # the new row in new matrix
#    for j in range(len(B)):
#        product = 0 # the new element in the new row
#        for v in range(len(A[i])):
#            product += A[i][v] * B[v][j]
#        row.append(product) # append sum of product into the new row
#    C.append(row) # append the new row into the final result

X,Y = np.shape(B) 
print(Y)

C = [] #final result
for i in range(len(A)):
    for j in range(Y):
        product = 0
        for k in range(len(A[i])):
            product += A[i][k] * B[k][j]
            C.append(product)
        
print(C)

#1B
c_out = [[A[i][v]*B[v][j] for j in range(len(B))]for i in range(len(A))for v in range(len(A[i]))]
print(c_out)

#1C
D = np.matmul(A,B)
print(D)

#2

print(D[:2,0:2])

[[ 6.  4.  2.]
 [ 1.  3.  2.]
 [10.  1.  4.]
 [ 0.  8.  4.]]
[[4. 4. 2. 0. 3.]
 [8. 6. 2. 2. 4.]
 [7. 7. 2. 4. 1.]]
5
[24.0, 56.0, 70.0, 24.0, 48.0, 62.0, 12.0, 20.0, 24.0, 0.0, 8.0, 16.0, 18.0, 34.0, 36.0, 4.0, 28.0, 42.0, 4.0, 22.0, 36.0, 2.0, 8.0, 12.0, 0.0, 6.0, 14.0, 3.0, 15.0, 17.0, 40.0, 48.0, 76.0, 40.0, 46.0, 74.0, 20.0, 22.0, 30.0, 0.0, 2.0, 18.0, 30.0, 34.0, 38.0, 0.0, 64.0, 92.0, 0.0, 48.0, 76.0, 0.0, 16.0, 24.0, 0.0, 16.0, 32.0, 0.0, 32.0, 36.0]
[[24.0, 24.0, 12.0], [32.0, 24.0, 8.0], [14.0, 14.0, 4.0], [4.0, 4.0, 2.0], [24.0, 18.0, 6.0], [14.0, 14.0, 4.0], [40.0, 40.0, 20.0], [8.0, 6.0, 2.0], [28.0, 28.0, 8.0], [0.0, 0.0, 0.0], [64.0, 48.0, 16.0], [28.0, 28.0, 8.0]]
[[70. 62. 24. 16. 36.]
 [42. 36. 12. 14. 17.]
 [76. 74. 30. 18. 38.]
 [92. 76. 24. 32. 36.]]
[[70. 62.]
 [42. 36.]]


In [55]:
D = np.matmul(A,B)
print(D)

#2

print(D[:2,0:2])

[[70. 62. 24. 16. 36.]
 [42. 36. 12. 14. 17.]
 [76. 74. 30. 18. 38.]
 [92. 76. 24. 32. 36.]]
[[70. 62.]
 [42. 36.]]


In [51]:
C = [] #final result
for i in range(np.shape(A)[0]): #- i is for every row in A
    new_row = []
    for j in range(np.shape(B)[1]): #- j is for every col in B
        product = 0
        for k in range(np.shape(A)[1]): #- loop over inner dimension
            product += A[i,k] * B[k,j]
        new_row.append(product)    
    C.append(new_row)
        
print (np.array(C))

[[ 62.  26.  42.  56.  60.]
 [ 92.  68.  80. 112. 108.]
 [ 56.  38.  51.  66.  76.]
 [ 45.  27.  48.  52.  85.]]


In [45]:
A[i,k]

3.0

In [12]:
# A 4 x 3
# B 3 x 5

# first element = dot product of first row in A x first column in B
# second element = dot product of first row in A x second column in B

# 1. for loop that will print rows of A
# 2. for each loop of A, sub loop print columns of B
# 3. dot product of row of A and column of B (ai . bj)


array([[10.,  1.,  0.],
       [ 9.,  5.,  9.],
       [ 7.,  2.,  1.],
       [ 6.,  8.,  2.]])