## EXERCISES

### Vector Multiplication
1. Produce 2 vectors, one with integers in the range [5,10] and the other [15,20] using the np.arange function
1. Without using any functions from the numpy module
    1. Compute the outer product of those vectors 
    1. Compute the "trace" of the resulting matrix
    
    ![trace](https://wikimedia.org/api/rest_v1/media/math/render/svg/3e5b6e82272fc5eeca6d510388e0a2bd0a6c6463)
    
    
Complete the same items using numpy operations

In [42]:
# 1 
x = np.arange(5,11)
print(x)
y = np.arange(15,21)
print(y)

# 2A 
c_out = [[x[i]*y[j] for j in range(len(y))]for i in range(len(x))]
print('Outer Product:') # Print Output
c_out

n_out = np.outer(x,y)
n_out

# 2B
np.trace(n_out)

[ 5  6  7  8  9 10]
[15 16 17 18 19 20]
Outer Product:
Object `trace` not found.


### Matrix Multiplication
* Two matricies can be multiplied if their inner dimensions match (eg. 2x3 * 3x5 -> 2x5). The best rule for working with and mutliplying matricies is to remember (rows x columns). This applies to both the dimensions of a matrix (a 2x3 matrix has 2 rows and 3 columns) as well as multiplication (you multiply the rows of the first matrix by the columns of the second). 

* When multiplying two matricies of dimension (M x N)*(N x P) the resulting matrix is (M x P). The upper element of the reslting matrix is the inner (or dot) product of the first row of the first matrix and the first column of the second matrix

![two matrices](https://wikimedia.org/api/rest_v1/media/math/render/svg/16b1644351bc2041175b19cbc65da03ef78130c7)

![store product in matrix C](https://wikimedia.org/api/rest_v1/media/math/render/svg/00ac0c831c365b7424cc43239aae8cebea27c56c)

![matrix multiply](https://wikimedia.org/api/rest_v1/media/math/render/svg/3cfeccef1c8c7e6da0ddf08daed8dbf3c6f50c5e)

for i = 1, ..., n and j = 1, ..., p.

1. Make two matrices of random numbers (A and B). A should be a 4x3 matrix and B should be a 3x4 matrix. Multiply A by B using (to a resulting matrix C) using:
    1. a conventional for-loop
    1. list comprehension
    1. numpy operator
    
2. After you have C, pull out the upper quadrant using fancy indexing, and then replace the main diagonal (upper left to lower right) with 0s. 

In [99]:
#1
A = np.round(np.random.rand(4,3)*10)
print(A)

B = np.round(np.random.rand(3,4)*10)
print(B)
  
#1A
C = []

for i in range(len(A)): 
    row = [] 
    for j in range(len(B)):
        for k in range(len(B[0])):
            row.append(A[i][k]*B[k][j])
        
    p_out.append(row)
print(C)


#1B
c_out = [[A[i]*B[j] for j in range(len(B))]for i in range(len(A))]
print(c_out)

#1C
C = np.outer(A,B)
print(C)

#2

print(C[:2,0:2])

[[4. 1. 4.]
 [2. 9. 8.]
 [5. 8. 1.]
 [9. 1. 5.]]
[[8. 4. 8. 5.]
 [8. 2. 4. 9.]
 [6. 6. 6. 4.]]


IndexError: index 3 is out of bounds for axis 0 with size 3

Object `append` not found.
