# Indexing and slicing and iterating in NumPy

In [1]:
# import numpy
import numpy as np

In [3]:
# create a 1d array
x = np.linspace(0,9,10)
print(x)
x[1]                     # just the second entry, remember 0 based indexing

# specific start and stop points (exclusive)
x[0:2]                   # the first and second entries in the array, so N>=0 and N<2 (note the < upper bound - not inclusive)

# assign the 2nd - 4th element to 100 (index 1,2,3)
x[1:4] = 100               
print(x[1:4])

# start, stop, step interval
print(x[0:8:2])

# reverse x
print(x[::-1])

# iterate over all elements in x
for i in x:
    print(i*3)    # then i takes the value of each element in x, go through every element and mult by 3

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[100. 100. 100.]
[  0. 100.   4.   6.]
[  9.   8.   7.   6.   5.   4. 100. 100. 100.   0.]
0.0
300.0
300.0
300.0
12.0
15.0
18.0
21.0
24.0
27.0


## multidimentional array indexing, slicing etc

In [18]:
x = np.round(np.random.rand(10,5)*10)   # generate a matrix of uniformly distributed random numbers over 0:10
print(x)

x[0,0]     # first row, first column bc 0 based counting
x[2,3]     # third row, 4th column

x[:, 3]    # all entries in the 4th column 
x[3, :]    # all entries in the 4th row
x[0:2, 4]  # first two entries of the 5th column
x[6, 2:4]  # 7th row, 3rd and 4th entries. 

x[6]       # if not all dims specified then missing values are considered complete slices
x[6,]      # these three ways of writing all do the same thing...
x[6,:]

# tricks...
print('last row: ', x[-1,:])     # last row
print('last column: ', x[:,-1])  # last column
print('last entry: ', x[-1,-1])  # last value

# iterating goes over the first dim (rows); iterate over a matrix
for r in x:
     print(r)
        
# can also iterate over all entries in the array using 'flat'
# will proceed along 1st row, then to 2nd row, etc. 
for a in x.flat:
    print(a)

[[ 4.  9.  7.  8.  9.]
 [ 9.  9.  1.  1.  1.]
 [ 5.  7.  2.  9.  6.]
 [ 7.  2.  3.  6.  4.]
 [ 5.  8.  4.  6.  7.]
 [ 4.  7.  5.  4.  8.]
 [ 6.  5.  8.  4.  2.]
 [10.  9.  5. 10.  6.]
 [ 4.  1.  7. 10.  7.]
 [ 5.  2.  9.  7. 10.]]
last row:  [ 5.  2.  9.  7. 10.]
last column:  [ 9.  1.  6.  4.  7.  8.  2.  6.  7. 10.]
last entry:  10.0
[4. 9. 7. 8. 9.]
[9. 9. 1. 1. 1.]
[5. 7. 2. 9. 6.]
[7. 2. 3. 6. 4.]
[5. 8. 4. 6. 7.]
[4. 7. 5. 4. 8.]
[6. 5. 8. 4. 2.]
[10.  9.  5. 10.  6.]
[ 4.  1.  7. 10.  7.]
[ 5.  2.  9.  7. 10.]
4.0
9.0
7.0
8.0
9.0
9.0
9.0
1.0
1.0
1.0
5.0
7.0
2.0
9.0
6.0
7.0
2.0
3.0
6.0
4.0
5.0
8.0
4.0
6.0
7.0
4.0
7.0
5.0
4.0
8.0
6.0
5.0
8.0
4.0
2.0
10.0
9.0
5.0
10.0
6.0
4.0
1.0
7.0
10.0
7.0
5.0
2.0
9.0
7.0
10.0


## pull out subset of rows and columns

In [7]:
# generate a matrix of random numbers over 0-1
x = np.random.rand(4,3) 
print(x)

# first two rows - note that you don't have to specify the 2nd dim - and note that 
# '2' here means rows 0 and 1 (not 0 through 2!)
y = x[:2] 
print('\n', y)

# can also take the last two rows...in the same manner...in this case rows 3 and 4
y = x[2:] 
print('\n', y)

# first two rows, 1st column
y = x[:2,0] 
print('\n', y)

# rows 3 - end, columns 2 - end
y = x[2:,1:]
print('\n', y)

[[0.10051985 0.86246093 0.25721147]
 [0.52939855 0.91485333 0.2047236 ]
 [0.80290265 0.75090777 0.60950522]
 [0.95693181 0.76118708 0.83896274]]

 [[0.10051985 0.86246093 0.25721147]
 [0.52939855 0.91485333 0.2047236 ]]

 [[0.80290265 0.75090777 0.60950522]
 [0.95693181 0.76118708 0.83896274]]

 [0.10051985 0.52939855]

 [[0.75090777 0.60950522]
 [0.76118708 0.83896274]]


<div class="alert alert-info">
important - slicing an array creates a view of it! if you change the view, you also will change the original data!
</div>

In [8]:
z = x[:,] #z is a view of x, so if you change data in z, you are also changing it in x
print(z.shape)

# change all values in z using [:]
z[:]=100     # so if you change data in z it will also change in x

print(x)

(4, 3)
[[100. 100. 100.]
 [100. 100. 100.]
 [100. 100. 100.]
 [100. 100. 100.]]


## Fancy indexing...using arrays to index arrays - used all the time in data analysis...

<div class="alert alert-info">
fancy indexing always makes a COPY of the data (unlike slicing which creates a view)!!!
</div>

In [22]:
# define an array
x = np.random.rand(3,4)

# index array - can be a tuple
y = (2,3)

# index
print(x)
print('\n x indexed at tuple y: ', x[y])

[[0.04642286 0.37668279 0.00105533 0.00908313]
 [0.45754245 0.35047791 0.89388063 0.62333764]
 [0.69005657 0.64736177 0.01317135 0.6844905 ]]

 x indexed at tuple y:  0.6844905035840817


In [23]:
# can use fancy indexing to extract elements in a particular order
print(x)

# this will extract the 3rd row, then the 2nd row, then the first row
x[[2,1,0]]

# and this will extract all rows from the 2nd, 3rd and then 1st column. 
x[:,[1,2,0]]

[[0.04642286 0.37668279 0.00105533 0.00908313]
 [0.45754245 0.35047791 0.89388063 0.62333764]
 [0.69005657 0.64736177 0.01317135 0.6844905 ]]


array([[0.37668279, 0.00105533, 0.04642286],
       [0.35047791, 0.89388063, 0.45754245],
       [0.64736177, 0.01317135, 0.69005657]])

In [24]:
# or can pass in multiple arrays...will return a 1D array 
# corresponding to each set of tuples (1,1) and (2,2) in this case
# set of coordinates
print(x)
x[[1,2],[1,2]]

[[0.04642286 0.37668279 0.00105533 0.00908313]
 [0.45754245 0.35047791 0.89388063 0.62333764]
 [0.69005657 0.64736177 0.01317135 0.6844905 ]]


array([0.35047791, 0.01317135])

<div class="alert alert-info">
As opposed to selecting a set of tuples, you can also select a block of indices from a matrix. 
</div>

In [44]:
# grab the lower right chunk of data. 
print(x, '/n')

print(x[:2,0:2],'/n')
print(x[[1,2]][:,[2,3]])  # 2nd term here extracts all rows from columns, first arg says restrict to last two rows. 

[[0.04642286 0.37668279 0.00105533 0.00908313]
 [0.45754245 0.35047791 0.89388063 0.62333764]
 [0.69005657 0.64736177 0.01317135 0.6844905 ]] /n
[[0.04642286 0.37668279]
 [0.45754245 0.35047791]] /n
[[0.89388063 0.62333764]
 [0.01317135 0.6844905 ]]
